---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  annotations:
    description: Deployment template for a OCR - activemq largefiles service.
    tags: "${APP_NAME}"
  name: "${APP_NAME}-deploy"
objects:
- kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: "${APP_NAME}"
    labels:
      app: "${APP_NAME}"
      app-group: "${APP_GROUP}"
      template: "${APP_NAME}-deploy"
  spec:
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
    replicas: 1
    selector:
      matchLabels:
        app: "${APP_NAME}"
    template:
      metadata:
        labels:
          app: "${APP_NAME}"
          app-group: "${APP_GROUP}"
          deploymentconfig: "${APP_NAME}"
          template: "${APP_NAME}-deploy"
      spec:
        containers:
        - name: "${APP_NAME}"
          image: "${APP_NAME}"
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: OCR_REDIS_HOST
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: OCR_REDIS_PASSWORD
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: OCR_REDIS_PORT
            - name: OCR_STREAM_KEY
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: OCR_STREAM_KEY_LARGEFILES
            - name: NOTIFICATION_STREAM_KEY
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: NOTIFICATION_STREAM_KEY
            - name: OCR_S3_ENV
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: OCR_S3_ENV
            - name: OCR_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: OCR_DB_HOST
            - name: OCR_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: OCR_DB_NAME
            - name: OCR_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: OCR_DB_PORT
            - name: OCR_DB_USER
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: OCR_DB_USER
            - name: OCR_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: OCR_DB_PASSWORD
            - name: OCR_S3_HOST
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: OCR_S3_HOST
            - name: OCR_S3_REGION
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: OCR_S3_REGION
            - name: OCR_S3_SERVICE
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: OCR_S3_SERVICE
          resources:
            requests:
              cpu: "50m"
              memory: "250Mi"
            limits:
              cpu: "150m"
              memory: "500Mi"
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          imagePullPolicy: Always
          image: 'image-registry.openshift-image-registry.svc:5000/d106d6-tools/${IMAGE_STREAM_NAME_FULL}'
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
  # status:
  #   loadBalancer: {}
parameters:
- name: APP_NAME
  displayName: Name
  description: The name assigned to all of the OpenShift resources associated to the
    server instance.
  required: true
  value: reviewer-ocr-largefiles
- name: APP_GROUP
  displayName: App Group
  description: The name assigned to all of the deployments in this project.
  required: true
  value: foi-docreviewer
- name: IMAGE_NAMESPACE
  displayName: Image Namespace
  required: true
  description: The namespace of the OpenShift project containing the imagestream for
    the application.
  value: d106d6-tools
- name: TAG_NAME
  displayName: Environment TAG name
  description: The TAG name for this environment, e.g., dev, test, prod
  required: true
  value: test-marshal
- name: SECRETS
  displayName: OCR Secrets
  description: Name of secrets for all ocr values
  required: true
  value: ocr-secret
- name: IMAGE_STREAM_NAME_FULL
  displayName: Full image stream name (eg "reviewer-ocr:test-marshal")
  description: Includes ImageStream name and tag
  required: true
  value: reviewer-ocr-largefiles:test-marshal
