apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}
  labels:
    app: ${NAME}
    name: ${NAME}
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}
    stringData:
      REDIS_HOST: "${OCR_REDIS_HOST}"
      REDIS_PASSWORD: "${OCR_REDIS_PASSWORD}"
      REDIS_PORT: "${OCR_REDIS_PORT}"
      OCR_STREAM_KEY: '${OCR_STREAM_KEY}'
      OCR_DB_HOST: '${OCR_DB_HOST}'
      OCR_DB_NAME: '${OCR_DB_NAME}'
      OCR_DB_PORT: '${OCR_DB_PORT}'
      OCR_DB_USER: '${OCR_DB_USER}'
      OCR_DB_PASSWORD: '${OCR_DB_PASSWORD}'
      OCR_S3_HOST: '${OCR_S3_HOST}'   
      OCR_S3_REGION: '${OCR_S3_REGION}'
      OCR_S3_SERVICE: '${OCR_S3_SERVICE}'
      OCR_S3_ENV: '${OCR_S3_ENV}'
    type: Opaque

parameters:
  - name: NAME
    description: The name for all created objects.
    required: true
  - name: OCR_REDIS_HOST
    description: OCR_REDIS_HOST
    required: true
  - name: OCR_REDIS_PASSWORD
    description: OCR_REDIS_PASSWORD
    required: true
  - name: OCR_REDIS_PORT
    description: OCR_REDIS_PORT
    required: true
  - name: OCR_STREAM_KEY
    description: OCR_STREAM_KEY
    required: true
  - name: OCR_DB_HOST
    description: OCR_DB_HOST
    required: true
  - name: OCR_DB_NAME
    description: OCR_DB_NAME
    required: true
  - name: OCR_DB_PORT
    description: OCR_DB_PORT
    required: true
  - name: OCR_DB_USER
    description: OCR_DB_USER
    required: true
  - name: OCR_DB_PASSWORD
    description: OCR_DB_PASSWORD
    required: true
  - name: OCR_S3_HOST
    description: OCR_S3_HOST
    required: true  
  - name: OCR_S3_REGION
    description: OCR_S3_REGION
    required: true
  - name: OCR_S3_SERVICE
    description: OCR_S3_SERVICE
    required: true
  - name: OCR_S3_ENV
    description: OCR_S3_ENV
    required: true