apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}
  labels:
    app: ${NAME}
    name: ${NAME}
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}
    stringData:    
      AZDOCOCR_FOIDOCREVIEWER_DB_HOST: "${AZDOCOCR_FOIDOCREVIEWER_DB_HOST}"
      AZDOCOCR_FOIDOCREVIEWER_DB_PORT: "${AZDOCOCR_FOIDOCREVIEWER_DB_PORT}"
      AZDOCOCR_FOIDOCREVIEWER_DB_NAME: '${AZDOCOCR_FOIDOCREVIEWER_DB_NAME}'
      AZDOCOCR_FOIDOCREVIEWER_DB_USERNAME: '${AZDOCOCR_FOIDOCREVIEWER_DB_USERNAME}'
      AZDOCOCR_FOIDOCREVIEWER_DB_PASSWORD: '${AZDOCOCR_FOIDOCREVIEWER_DB_PASSWORD}'
      AZDOCOCR_LISTENING_PORT: '${AZDOCOCR_LISTENING_PORT}'
      AZDOCOCR_API_SECRET: '${AZDOCOCR_API_SECRET}'
      AZDOCOCR_ALLOWED_ORIGINS: '${AZDOCOCR_ALLOWED_ORIGINS}'
    type: Opaque

parameters:
  - name: NAME
    description: The name for all created objects.
    required: true
    value: azuredococrapi-secret-test-rook
  - name: AZDOCOCR_FOIDOCREVIEWER_DB_HOST
    description: AZDOCOCR_FOIDOCREVIEWER_DB_HOST
    required: true
  - name: AZDOCOCR_FOIDOCREVIEWER_DB_PORT
    description: AZDOCOCR_FOIDOCREVIEWER_DB_PORT
    required: true
  - name: AZDOCOCR_FOIDOCREVIEWER_DB_NAME
    description: AZDOCOCR_FOIDOCREVIEWER_DB_NAME
    required: true
  - name: AZDOCOCR_FOIDOCREVIEWER_DB_USERNAME
    description: AZDOCOCR_FOIDOCREVIEWER_DB_USERNAME
    required: true
  - name: AZDOCOCR_FOIDOCREVIEWER_DB_PASSWORD
    description: AZDOCOCR_FOIDOCREVIEWER_DB_PASSWORD
    required: true
  - name: AZDOCOCR_LISTENING_PORT
    description: AZDOCOCR_LISTENING_PORT
    required: true
  - name: AZDOCOCR_API_SECRET
    description: AZDOCOCR_API_SECRET
    required: true
  - name: AZDOCOCR_ALLOWED_ORIGINS
    description: AZDOCOCR_ALLOWED_ORIGINS
    required: true
