apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}
  labels:
    app: ${NAME}
    name: ${NAME}
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}
    stringData:    
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_PASSWORD: '${REDIS_PASSWORD}'
      DOCUMENTSERVICE_DB_HOST: '${DOCUMENTSERVICE_DB_HOST}'
      DOCUMENTSERVICE_DB_NAME: '${DOCUMENTSERVICE_DB_NAME}'
      DOCUMENTSERVICE_DB_PORT: '${DOCUMENTSERVICE_DB_PORT}'
      PAGECALCULATOR_STREAM_KEY: '${PAGECALCULATOR_STREAM_KEY}'
      FOI_DB_HOST: '${FOI_DB_HOST}'
      FOI_DB_NAME: '${FOI_DB_NAME}'
      FOI_DB_PORT: '${FOI_DB_PORT}'
      FOI_DB_USER: '${FOI_DB_USER}'
      FOI_DB_PASSWORD: '${FOI_DB_PASSWORD}'

    type: Opaque

parameters:
  - name: NAME
    description: The name for all created objects.
    required: true
    value: pagecountcalculator-secret
  - name: REDIS_HOST
    description: REDIS_HOST
    required: true
  - name: REDIS_PORT
    description: REDIS_PORT
    required: true
  - name: REDIS_PASSWORD
    description: REDIS_PASSWORD
    required: true
  - name: DOCUMENTSERVICE_DB_HOST
    description: DOCUMENTSERVICE_DB_HOST
    required: true
  - name: DOCUMENTSERVICE_DB_NAME
    description: DOCUMENTSERVICE_DB_NAME
    required: true
  - name: DOCUMENTSERVICE_DB_PORT
    description: DOCUMENTSERVICE_DB_PORT
    required: true
  - name: PAGECALCULATOR_STREAM_KEY
    description: PAGECALCULATOR_STREAM_KEY
    required: true
  - name: FOI_DB_HOST
    description: FOI_DB_HOST
    required: true
  - name: FOI_DB_NAME
    description: FOI_DB_NAME
    required: true
  - name: FOI_DB_PORT
    description: FOI_DB_PORT
    required: true  
  - name: FOI_DB_USER
    description: FOI_DB_USER
    required: true
  - name: FOI_DB_PASSWORD
    description: FOI_DB_PASSWORD
    required: true