apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}
  labels:
    app: ${NAME}
    name: ${NAME}
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}
    stringData:
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_PASSWORD: '${REDIS_PASSWORD}'
      ZIPPER_STREAM_KEY: '${ZIPPER_STREAM_KEY}'
      DB_HOST: '${DB_HOST}'
      DB_NAME: '${DB_NAME}'
      DB_PORT: '${DB_PORT}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      S3_HOST: '${S3_HOST}'
      S3_REGION: '${S3_REGION}'
      S3_SERVICE: '${S3_SERVICE}'
      S3_ENV: '${S3_ENV}'
      NOTIFICATION_STREAM_KEY: '${NOTIFICATION_STREAM_KEY}'   
    type: Opaque

parameters:
  - name: NAME
    description: The name for all created objects.
    required: true
    value: zippingservice-secret
  - name: REDIS_HOST
    description: REDIS_HOST
    required: true
  - name: REDIS_PORT
    description: REDIS_PORT
    required: true
  - name: REDIS_PASSWORD
    description: REDIS_PASSWORD
    required: true
  - name: ZIPPER_STREAM_KEY
    description: ZIPPER_STREAM_KEY
    required: true
  - name: DB_HOST
    description: DB_HOST
    required: true
  - name: DB_NAME
    description: DB_NAME
    required: true
  - name: DB_PORT
    description: DB_PORT
    required: true
  - name: S3_HOST
    description: S3_HOST
    required: true
  - name: S3_REGION
    description: S3_REGION
    required: true
  - name: S3_SERVICE
    description: S3_SERVICE
    required: true  
  - name: S3_ENV
    description: S3_ENV
    required: true
  - name: NOTIFICATION_STREAM_KEY
    description: NOTIFICATION_STREAM_KEY
    required: true
  - name: DB_USER
    description: DB_USER
    required: true 
  - name: DB_PASSWORD
    description: DB_PASSWORD
    required: true     