CREATE TABLE "DocumentPathMapper" (
    documentpathid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category text NOT NULL,
    bucket text NOT NULL,
    attributes text,
    isactive boolean NOT NULL,
    createdby varchar(120),
    created_at timestamp DEFAULT now(),
    updatedby varchar(120),
    updated_at timestamp
);

CREATE TABLE "DocumentMaster" (
    documentmasterid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filepath varchar(500) NOT NULL,
    ministryrequestid integer NOT NULL,
    recordid integer,
    processingparentid integer,
    parentid integer,
    isredactionready boolean NOT NULL,
    created_at timestamp DEFAULT now(),
    createdby varchar(120),
    updated_at timestamp,
    updatedby varchar(120),
    compressedfilepath varchar(500),
    ocrfilepath varchar(500)
);

CREATE TABLE "DocumentAttributes" (
    attributeid integer GENERATED BY DEFAULT AS IDENTITY,
    version integer NOT NULL,
    documentmasterid integer REFERENCES "DocumentMaster" (documentmasterid),
    attributes json NOT NULL,
    createdby json,
    created_at timestamp DEFAULT now(),
    updatedby json,
    updated_at timestamp,
    isactive boolean NOT NULL DEFAULT true,
    PRIMARY KEY (attributeid, version)
);

CREATE TABLE "FileConversionJob" (
    fileconversionjobid integer GENERATED BY DEFAULT AS IDENTITY,
    version integer NOT NULL,
    ministryrequestid integer NOT NULL,
    createdat timestamp NOT NULL DEFAULT now(),
    batch varchar(120) NOT NULL,
    trigger varchar(120) NOT NULL,
    inputdocumentmasterid integer NOT NULL,
    outputdocumentmasterid integer,
    filename varchar(500) NOT NULL,
    status varchar(120) NOT NULL,
    message text,
    PRIMARY KEY (fileconversionjobid, version)
);

CREATE TABLE "DeduplicationJob" (
    deduplicationjobid integer GENERATED BY DEFAULT AS IDENTITY,
    version integer NOT NULL,
    ministryrequestid integer NOT NULL,
    createdat timestamp NOT NULL DEFAULT now(),
    batch varchar(120) NOT NULL,
    type varchar(50) NOT NULL,
    trigger varchar(120) NOT NULL,
    documentmasterid integer NOT NULL,
    filename varchar(500) NOT NULL,
    status varchar(120) NOT NULL,
    message text,
    PRIMARY KEY (deduplicationjobid, version)
);
