apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}
  labels:
    app: ${NAME}
    name: ${NAME}
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}
    stringData:    
      DOCREVIEWER_DB_HOST: "${DOCREVIEWER_DB_HOST}"
      DOCREVIEWER_DB_NAME: "${DOCREVIEWER_DB_NAME}"
      DOCREVIEWER_DB_USER: '${DOCREVIEWER_DB_USER}'
      DOCREVIEWER_DB_PASSWORD: '${DOCREVIEWER_DB_PASSWORD}'
      DOCREVIEWER_DB_PORT: '${DOCREVIEWER_DB_PORT}'
      SOLR_ENDPOINT: '${SOLR_ENDPOINT}'
      SOLR_USERNAME: '${SOLR_USERNAME}'
      SOLR_PASSWORD: '${SOLR_PASSWORD}'
    type: Opaque

parameters:
  - name: NAME
    description: The name for all created objects.
    required: true
    value: removefromsolrcronjobsecrets
  - name: DOCREVIEWER_DB_HOST
    description: DOCREVIEWER_DB_HOST
    required: true
  - name: DOCREVIEWER_DB_NAME
    description: DOCREVIEWER_DB_NAME
    required: true
  - name: DOCREVIEWER_DB_USER
    description: DOCREVIEWER_DB_USER
    required: true
  - name: DOCREVIEWER_DB_PASSWORD
    description: DOCREVIEWER_DB_PASSWORD
    required: true
  - name: DOCREVIEWER_DB_PORT
    description: DOCREVIEWER_DB_PORT
    required: true
  - name: SOLR_ENDPOINT
    description: SOLR_ENDPOINT
    required: true
  - name: SOLR_USERNAME
    description: SOLR_USERNAME
    required: true
  - name: SOLR_PASSWORD
    description: SOLR_PASSWORD
    required: true
