apiVersion: batch/v1
kind: CronJob
metadata:
  name: restart-pods
  namespace: xxxxxx-xxx
spec:
  schedule: "0 3 * * *"
  timeZone: America/Vancouver
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: restart-pods
              image: openshift/origin-cli:latest
              command:
                - "sh"
                - "-c"
                - |
                  oc patch dc/reviewer-dedupe -p "{\"spec\":{\"replicas\": 0}}"
                  sleep 30s
                  oc rollout latest reviewer-dedupe
                  sleep 30s
                  oc patch dc/reviewer-dedupe -p "{\"spec\":{\"replicas\": 1}}"
                  sleep 30s

                  oc patch dc/reviewer-dedupe-largefiles -p "{\"spec\":{\"replicas\": 0}}"
                  sleep 30s
                  oc rollout latest reviewer-dedupe-largefiles
                  sleep 30s
                  oc patch dc/reviewer-dedupe-largefiles -p "{\"spec\":{\"replicas\": 1}}"
                  sleep 30s

                  oc patch dc/reviewer-conversion -p "{\"spec\":{\"replicas\": 0}}"
                  sleep 30s
                  oc rollout latest reviewer-conversion
                  sleep 30s
                  oc patch dc/reviewer-conversion -p "{\"spec\":{\"replicas\": 1}}"
                  sleep 30s

                  oc patch dc/reviewer-conversion-largefiles -p "{\"spec\":{\"replicas\": 0}}"
                  sleep 30s
                  oc rollout latest reviewer-conversion-largefiles
                  sleep 30s
                  oc patch dc/reviewer-conversion-largefiles -p "{\"spec\":{\"replicas\": 1}}"
                  sleep 30s

                  oc patch dc/reviewer-pdfstitch -p "{\"spec\":{\"replicas\": 0}}"
                  sleep 30s
                  oc rollout latest reviewer-pdfstitch
                  sleep 30s
                  oc patch dc/reviewer-pdfstitch -p "{\"spec\":{\"replicas\": 1}}"
                  sleep 30s

                  oc patch dc/reviewer-pdfstitch-largefiles -p "{\"spec\":{\"replicas\": 0}}"
                  sleep 30s
                  oc rollout latest reviewer-pdfstitch-largefiles
                  sleep 30s
                  oc patch dc/reviewer-pdfstitch-largefiles -p "{\"spec\":{\"replicas\": 1}}"
                  sleep 30s

                  oc patch dc/reviewer-zippingservice -p "{\"spec\":{\"replicas\": 0}}"
                  sleep 30s
                  oc rollout latest reviewer-zippingservice
                  sleep 30s
                  oc patch dc/reviewer-zippingservice -p "{\"spec\":{\"replicas\": 1}}"
                  sleep 30s

                  oc patch dc/reviewer-documentservice-test -p "{\"spec\":{\"replicas\": 0}}"
                  sleep 30s
                  oc rollout latest reviewer-documentservice-test
                  sleep 30s
                  oc patch dc/reviewer-documentservice-test -p "{\"spec\":{\"replicas\": 1}}"
                  sleep 30s

          restartPolicy: OnFailure
