apiVersion: batch/v1
kind: CronJob
metadata:
  name: restart-pods
  namespace: d106d6-dev
spec:
  schedule: "0 11 * * *"
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: restart-pods
              image: openshift/origin-cli:latest
              command:
                - "sh"
                - "-c"
                - |
                  oc rollout latest reviewer-dedupe
                  sleep 30s
                  oc rollout latest reviewer-dedupe-largefiles
                  sleep 30s
                  oc rollout latest reviewer-conversion
                  sleep 30s
                  oc rollout latest reviewer-conversion-largefiles
                  sleep 30s
                  oc rollout latest reviewer-pdfstitch
                  sleep 30s
                  oc rollout latest reviewer-pdfstitch-largefiles
          restartPolicy: OnFailure
