---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  annotations:
    description: Deployment template for a file conversion app.
    tags: "${APP_NAME}"
  name: "${APP_NAME}-deploy"
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
    labels:
      app: "${APP_NAME}"
      app-group: "${APP_GROUP}"
      template: "${APP_NAME}-deploy"
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "${APP_NAME}"
        from:
          kind: ImageStreamTag
          namespace: "${IMAGE_NAMESPACE}"
          name: "${APP_NAME}:${TAG_NAME}"
    - type: ConfigChange
    replicas: 1
    test: false
    selector:
      app: "${APP_NAME}"
      deploymentconfig: "${APP_NAME}"
    template:
      metadata:
        labels:
          app: "${APP_NAME}"
          app-group: "${APP_GROUP}"
          deploymentconfig: "${APP_NAME}"
          template: "${APP_NAME}-deploy"
      spec:
        containers:
        - name: "${APP_NAME}"
          image: "${APP_NAME}"
          imagePullPolicy: Always
          env:
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: DATABASE_PASSWORD
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: DATABASE_NAME
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: DATABASE_PORT
            - name: S3_HOST
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: S3_HOST
            - name: S3_REGION
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: S3_REGION
            - name: S3_SERVICE
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: S3_SERVICE
            - name: REDIS_STREAM_HOST
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: REDIS_STREAM_HOST
            - name: REDIS_STREAM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: REDIS_STREAM_PASSWORD
            - name: REDIS_STREAM_PORT
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: REDIS_STREAM_PORT
            - name: REDIS_STREAM_KEY
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: REDIS_STREAM_KEY
            - name: REDIS_STREAM_CONSUMER_GROUP
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: REDIS_STREAM_CONSUMER_GROUP
           resources:
            requests:
              cpu: "50m"
              memory: "250Mi"
            limits:
              cpu: "150m"
              memory: "500Mi"
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
  # status:
  #   loadBalancer: {}
parameters:
- name: APP_NAME
  displayName: Name
  description: The name assigned to all of the OpenShift resources associated to the
    server instance.
  required: true
  value: reviewer-conversion
- name: APP_GROUP
  displayName: App Group
  description: The name assigned to all of the deployments in this project.
  required: true
  value: foi-docreviewer
- name: IMAGE_NAMESPACE
  displayName: Image Namespace
  required: true
  description: The namespace of the OpenShift project containing the imagestream for
    the application.
  value: d7abee-tools
- name: TAG_NAME
  displayName: Environment TAG name
  description: The TAG name for this environment, e.g., dev, test, prod
  required: true
  value: dev
- name: SECRETS
  displayName: File Conversion App Secrets
  description: Name of secret for all file conversion values
  required: true
  value: conversion-secret
