---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  annotations:
    description: Deployment template for a reviewer-pdfstitch service.
    tags: "${APP_NAME}"
  name: "${APP_NAME}-deploy"
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
    labels:
      app: "${APP_NAME}"
      app-group: "${APP_GROUP}"
      template: "${APP_NAME}-deploy"
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "${APP_NAME}"
        from:
          kind: ImageStreamTag
          namespace: "${IMAGE_NAMESPACE}"
          name: "${IMAGE_NAME}:${TAG_NAME}"
    - type: ConfigChange
    replicas: 1
    test: false
    selector:
      app: "${APP_NAME}"
      deploymentconfig: "${APP_NAME}"
    template:
      metadata:
        labels:
          app: "${APP_NAME}"
          app-group: "${APP_GROUP}"
          deploymentconfig: "${APP_NAME}"
          template: "${APP_NAME}-deploy"
      spec:
        containers:
        - name: "${APP_NAME}"
          image: "${APP_NAME}"
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: REDIS_HOST
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: REDIS_PASSWORD
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: REDIS_PORT
            - name: DIVISION_PDF_STITCH_STREAM_KEY
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: DIVISION_PDF_STITCH_STREAM_KEY
            - name: NOTIFICATION_REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: REDIS_HOST
            - name: NOTIFICATION_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: REDIS_PASSWORD
            - name: NOTIFICATION_REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: REDIS_PORT
            - name: NOTIFICATION_STREAM_KEY
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: NOTIFICATION_STREAM_KEY
            - name: PDFSTITCH_S3_ENV
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: PDFSTITCH_S3_ENV
            - name: PDFSTITCH_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: PDFSTITCH_DB_HOST
            - name: PDFSTITCH_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: PDFSTITCH_DB_NAME
            - name: PDFSTITCH_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: PDFSTITCH_DB_PORT
            - name: PDFSTITCH_DB_USER
              valueFrom:
                secretKeyRef:
                  name: "${DB_SECRETS}"
                  key: app-db-username
            - name: PDFSTITCH_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "${DB_SECRETS}"
                  key: app-db-password
            - name: PDFSTITCH_S3_HOST
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: PDFSTITCH_S3_HOST
            - name: PDFSTITCH_S3_REGION
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: PDFSTITCH_S3_REGION
            - name: PDFSTITCH_S3_SERVICE
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: PDFSTITCH_S3_SERVICE
            - name: DIVISION_STITCH_FOLDER_PATH
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: DIVISION_STITCH_FOLDER_PATH
            - name: NUMBERING_ENABLED
              value: "${NUMBERING_ENABLED}"
            - name: NOTIFICATION_ENABLED
              value: "${NOTIFICATION_ENABLED}"
            - name: MESSAGE_BLOCK_TIME
              value: "${MESSAGE_BLOCK_TIME}"
            - name: HEALTH_CHECK_INTERVAL
              value: "${HEALTH_CHECK_INTERVAL}"
            - name: PDF_STITCH_FAILUREATTEMPT
              value: "${PDF_STITCH_FAILUREATTEMPT}"    
          resources:
            requests:
              cpu: "50m"
              memory: "250Mi"
            limits:
              cpu: "150m"
              memory: "500Mi"     
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
- kind: Service
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
    creationTimestamp: 
    labels:
      app: "${APP_NAME}"
      app-group: "${APP_GROUP}"
      template: "${APP_NAME}-deploy"
  spec:
    ports:
    - name: 5000-tcp
      protocol: TCP
      port: 5000
      targetPort: 5000
    selector:
      deploymentconfig: "${APP_NAME}"
    type: ClusterIP
    sessionAffinity: None
  # status:
  #   loadBalancer: {}
- kind: Route
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
    labels:
      app: "${APP_NAME}"
      app-group: "${APP_GROUP}"
      template: "${APP_NAME}-deploy"
  spec:
    to:
      kind: Service
      name: "${APP_NAME}"
      weight: 100
    port:
      targetPort: 5000-tcp
    tls:
      termination: edge
    wildcardPolicy: None
    host: "${APP_NAME}-${TAG_NAME}.apps.silver.devops.gov.bc.ca"
parameters:
- name: APP_NAME
  displayName: Name
  description: The name assigned to all of the OpenShift resources associated to the
    server instance.
  required: true
  value: reviewer-pdfstitch-largefiles
- name: APP_GROUP
  displayName: App Group
  description: The name assigned to all of the deployments in this project.
  required: true
  value: foi-docreviewer
- name: IMAGE_NAMESPACE
  displayName: Image Namespace
  required: true
  description: The namespace of the OpenShift project containing the imagestream for
    the application.
- name: IMAGE_NAME
  displayName: Name
  description: The name assigned to all of the OpenShift resources associated to the
    server instance.
  required: true
  value: reviewer-pdfstitch
- name: TAG_NAME
  displayName: Environment TAG name
  description: The TAG name for this environment, e.g., dev, test, prod
  required: true
- name: DB_SECRETS
  displayName: Patroni DB Secrets
  description: Name of secrets for all db values
  required: true
- name: SECRETS
  displayName: PDFStitch Secrets
  description: Name of secrets for all pdfstitch values
  required: true
- name: NUMBERING_ENABLED
  displayName: NUMBERING_ENABLED
  description: Value for property 
  required: true
- name: NOTIFICATION_ENABLED
  displayName: NOTIFICATION_ENABLED
  description: Value for property 
  required: true
- name: MESSAGE_BLOCK_TIME
  displayName: MESSAGE_BLOCK_TIME
  description: Value for property 
  required: true
- name: HEALTH_CHECK_INTERVAL
  displayName: HEALTH_CHECK_INTERVAL
  description: Value for property 
  required: true
- name: PDF_STITCH_FAILUREATTEMPT
  displayName: PDF_STITCH_FAILUREATTEMPT
  description: Value for property 
  required: true
 