apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}
  labels:
    app: ${NAME}
    name: ${NAME}
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}
    stringData:
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_PASSWORD: '${REDIS_PASSWORD}'
      DIVISION_PDF_STITCH_STREAM_KEY: '${DIVISION_PDF_STITCH_STREAM_KEY}'
      PDFSTITCH_DB_HOST: '${PDFSTITCH_DB_HOST}'
      PDFSTITCH_DB_NAME: '${PDFSTITCH_DB_NAME}'
      PDFSTITCH_DB_PORT: '${PDFSTITCH_DB_PORT}'
      PDFSTITCH_S3_HOST: '${PDFSTITCH_S3_HOST}'
      PDFSTITCH_S3_REGION: '${PDFSTITCH_S3_REGION}'
      PDFSTITCH_S3_SERVICE: '${PDFSTITCH_S3_SERVICE}'
      PDFSTITCH_S3_ENV: '${PDFSTITCH_S3_ENV}'   

    type: Opaque

parameters:
  - name: NAME
    description: The name for all created objects.
    required: true
    value: pdfstitch-secret
  - name: REDIS_HOST
    description: REDIS_HOST
    required: true
  - name: REDIS_PORT
    description: REDIS_PORT
    required: true
  - name: REDIS_PASSWORD
    description: REDIS_PASSWORD
    required: true
  - name: DIVISION_PDF_STITCH_STREAM_KEY
    description: DIVISION_PDF_STITCH_STREAM_KEY
    required: true
  - name: PDFSTITCH_DB_HOST
    description: PDFSTITCH_DB_HOST
    required: true
  - name: PDFSTITCH_DB_NAME
    description: PDFSTITCH_DB_NAME
    required: true
  - name: PDFSTITCH_DB_PORT
    description: PDFSTITCH_DB_PORT
    required: true
  - name: PDFSTITCH_S3_HOST
    description: PDFSTITCH_S3_HOST
    required: true
  - name: PDFSTITCH_S3_REGION
    description: PDFSTITCH_S3_REGION
    required: true
  - name: PDFSTITCH_S3_SERVICE
    description: PDFSTITCH_S3_SERVICE
    required: true  
  - name: PDFSTITCH_S3_ENV
    description: PDFSTITCH_S3_ENV
    required: true