---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  annotations:
    description: Deployment template for a reviewer-documentservice.
    tags: "${APP_NAME}"
  name: "${APP_NAME}-deploy"
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
    labels:
      app: "${APP_NAME}"
      app-group: "${APP_GROUP}"
      template: "${APP_NAME}-deploy"
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "${APP_NAME}"
        from:
          kind: ImageStreamTag
          namespace: "${IMAGE_NAMESPACE}"
          name: "${IMAGE_APP_NAME}:${TAG_NAME}"
    - type: ConfigChange
    replicas: 1
    test: false
    selector:
      app: "${APP_NAME}"
      deploymentconfig: "${APP_NAME}"
    template:
      metadata:
        labels:
          app: "${APP_NAME}"
          app-group: "${APP_GROUP}"
          deploymentconfig: "${APP_NAME}"
          template: "${APP_NAME}-deploy"
      spec:
        containers:
        - name: "${APP_NAME}"
          image: "${APP_NAME}"
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: DOCUMENTSERVICE_REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: DOCUMENTSERVICE_REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "${REDIS_SECRETS}"
                  key: database-password
            - name: DOCUMENTSERVICE_STREAM_KEY
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: DOCUMENTSERVICE_STREAM_KEY
            - name: ZIPPER_REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: ZIPPER_REDIS_HOST
            - name: ZIPPER_REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: ZIPPER_REDIS_PORT
            - name: ZIPPER_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "${REDIS_SECRETS}"
                  key: database-password
            - name: ZIPPER_STREAM_KEY
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: ZIPPER_STREAM_KEY
            - name: DOCUMENTSERVICE_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: DOCUMENTSERVICE_DB_HOST
            - name: DOCUMENTSERVICE_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: DOCUMENTSERVICE_DB_NAME
            - name: DOCUMENTSERVICE_DB_USER
              valueFrom:
                secretKeyRef:
                  name: "${DB_SECRETS}"
                  key: app-db-username
            - name: DOCUMENTSERVICE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "${DB_SECRETS}"
                  key: app-db-password
            - name: DOCUMENTSERVICE_S3_HOST
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: DOCUMENTSERVICE_S3_HOST
            - name: DOCUMENTSERVICE_S3_REGION
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: DOCUMENTSERVICE_S3_REGION
            - name: DOCUMENTSERVICE_S3_SERVICE
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: DOCUMENTSERVICE_S3_SERVICE
            - name: DOCUMENTSERVICE_S3_ENV
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: DOCUMENTSERVICE_S3_ENV
            - name: CDOGS_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: CDOGS_BASE_URL
            - name: CDOGS_TOKEN_URL
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: CDOGS_TOKEN_URL
            - name: CDOGS_SERVICE_CLIENT
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: CDOGS_SERVICE_CLIENT
            - name: CDOGS_SERVICE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: CDOGS_SERVICE_CLIENT_SECRET
            - name: FOI_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: FOI_DB_HOST
            - name: FOI_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: FOI_DB_PORT
            - name: FOI_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: FOI_DB_NAME
            - name: FOI_DB_USER
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: FOI_DB_USER
            - name: FOI_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "${SECRETS}"
                  key: FOI_DB_PASSWORD
          resources:
            requests:
              cpu: "50m"
              memory: "250Mi"
            limits:
              cpu: "150m"
              memory: "500Mi"     
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
- kind: Service
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
    creationTimestamp: 
    labels:
      app: "${APP_NAME}"
      app-group: "${APP_GROUP}"
      template: "${APP_NAME}-deploy"
  spec:
    ports:
    - name: 5000-tcp
      protocol: TCP
      port: 5000
      targetPort: 5000
    selector:
      deploymentconfig: "${APP_NAME}"
    type: ClusterIP
    sessionAffinity: None
  # status:
  #   loadBalancer: {}
- kind: Route
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
    labels:
      app: "${APP_NAME}"
      app-group: "${APP_GROUP}"
      template: "${APP_NAME}-deploy"
  spec:
    to:
      kind: Service
      name: "${APP_NAME}"
      weight: 100
    port:
      targetPort: 5000-tcp
    tls:
      termination: edge
    wildcardPolicy: None
    host: "${APP_NAME}-${TAG_NAME}.apps.silver.devops.gov.bc.ca"
parameters:
- name: APP_NAME
  displayName: Name
  description: The name assigned to all of the OpenShift resources associated to the
    server instance.
  required: true
- name: IMAGE_APP_NAME
  displayName: Name
  description: The name assigned to all of the OpenShift resources associated to the
    server instance.
  required: true
- name: APP_GROUP
  displayName: App Group
  description: The name assigned to all of the deployments in this project.
  required: true
  value: foi-docreviewer
- name: IMAGE_NAMESPACE
  displayName: Image Namespace
  required: true
  description: The namespace of the OpenShift project containing the imagestream for
    the application.
- name: TAG_NAME
  displayName: Environment TAG name
  description: The TAG name for this environment, e.g., dev, test, prod
  required: true
- name: DB_SECRETS
  displayName: Patroni DB Secrets
  description: Name of secrets for all db values
  required: true
- name: SECRETS
  displayName: Documentservice Secrets
  description: Name of secrets for all documentservice values
  required: true
- name: REDIS_SECRETS
  displayName: Redis Secrets
  description: Name of secrets for redis
  required: true