apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}
  labels:
    app: ${NAME}
    name: ${NAME}
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}
    stringData:
      DOCUMENTSERVICE_REDIS_HOST: "${DOCUMENTSERVICE_REDIS_HOST}"
      DOCUMENTSERVICE_REDIS_PORT: "${DOCUMENTSERVICE_REDIS_PORT}"
      DOCUMENTSERVICE_STREAM_KEY: '${DOCUMENTSERVICE_STREAM_KEY}'
      ZIPPER_REDIS_HOST: '${ZIPPER_REDIS_HOST}'
      ZIPPER_REDIS_PORT: '${ZIPPER_REDIS_PORT}'
      ZIPPER_STREAM_KEY: '${ZIPPER_STREAM_KEY}'
      DOCUMENTSERVICE_DB_HOST: '${DOCUMENTSERVICE_DB_HOST}'
      DOCUMENTSERVICE_DB_NAME: '${DOCUMENTSERVICE_DB_NAME}'
      DOCUMENTSERVICE_S3_HOST: '${DOCUMENTSERVICE_S3_HOST}'   
      DOCUMENTSERVICE_S3_REGION: '${DOCUMENTSERVICE_S3_REGION}'
      DOCUMENTSERVICE_S3_SERVICE: '${DOCUMENTSERVICE_S3_SERVICE}'
      DOCUMENTSERVICE_S3_ENV: '${DOCUMENTSERVICE_S3_ENV}'
      CDOGS_BASE_URL: '${CDOGS_BASE_URL}'
      CDOGS_TOKEN_URL: '${CDOGS_TOKEN_URL}'
      CDOGS_SERVICE_CLIENT: '${CDOGS_SERVICE_CLIENT}'
      CDOGS_SERVICE_CLIENT_SECRET: '${CDOGS_SERVICE_CLIENT_SECRET}'
      FOI_DB_HOST: '${FOI_DB_HOST}'
      FOI_DB_PORT: '${FOI_DB_PORT}'
      FOI_DB_NAME: '${FOI_DB_NAME}'
      FOI_DB_USER: '${FOI_DB_USER}'
      FOI_DB_PASSWORD: '${FOI_DB_PASSWORD}'
    type: Opaque

parameters:
  - name: NAME
    description: The name for all created objects.
    required: true
  - name: DOCUMENTSERVICE_REDIS_HOST
    description: DOCUMENTSERVICE_REDIS_HOST
    required: true
  - name: DOCUMENTSERVICE_REDIS_PORT
    description: DOCUMENTSERVICE_REDIS_PORT
    required: true
  - name: DOCUMENTSERVICE_STREAM_KEY
    description: DOCUMENTSERVICE_STREAM_KEY
    required: true
  - name: ZIPPER_REDIS_HOST
    description: ZIPPER_REDIS_HOST
    required: true
  - name: ZIPPER_REDIS_PORT
    description: ZIPPER_REDIS_PORT
    required: true
  - name: ZIPPER_STREAM_KEY
    description: ZIPPER_STREAM_KEY
    required: true
  - name: DOCUMENTSERVICE_DB_HOST
    description: DOCUMENTSERVICE_DB_HOST
    required: true
  - name: DOCUMENTSERVICE_DB_NAME
    description: DOCUMENTSERVICE_DB_NAME
    required: true
  - name: DOCUMENTSERVICE_S3_HOST
    description: DOCUMENTSERVICE_S3_HOST
    required: true  
  - name: DOCUMENTSERVICE_S3_REGION
    description: DOCUMENTSERVICE_S3_REGION
    required: true
  - name: DOCUMENTSERVICE_S3_SERVICE
    description: DOCUMENTSERVICE_S3_SERVICE
    required: true
  - name: DOCUMENTSERVICE_S3_ENV
    description: DOCUMENTSERVICE_S3_ENV
    required: true
  - name: FOI_DB_HOST
    description: FOI_DB_HOST
    required: true
  - name: FOI_DB_PORT
    description: FOI_DB_PORT
    required: true  
  - name: FOI_DB_NAME
    description: FOI_DB_NAME
    required: true
  - name: FOI_DB_USER
    description: FOI_DB_USER
    required: true
  - name: FOI_DB_PASSWORD
    description: FOI_DB_PASSWORD
    required: true
  - name: CDOGS_SERVICE_CLIENT_SECRET
    description: CDOGS_SERVICE_CLIENT_SECRET
    required: true
  - name: CDOGS_SERVICE_CLIENT
    description: CDOGS_SERVICE_CLIENT
    required: true
  - name: CDOGS_TOKEN_URL
    description: CDOGS_TOKEN_URL
    required: true
  - name: CDOGS_BASE_URL
    description: CDOGS_BASE_URL
    required: true