apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}
  labels:
    app: ${NAME}
    name: ${NAME}
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}
    stringData:
      REDIS_HOST: "${COMPRESSION_REDIS_HOST}"
      REDIS_PASSWORD: "${COMPRESSION_REDIS_PASSWORD}"
      REDIS_PORT: "${COMPRESSION_REDIS_PORT}"
      COMPRESSION_STREAM_KEY: '${COMPRESSION_STREAM_KEY}'
      COMPRESSION_DB_HOST: '${COMPRESSION_DB_HOST}'
      COMPRESSION_DB_NAME: '${COMPRESSION_DB_NAME}'
      COMPRESSION_DB_PORT: '${COMPRESSION_DB_PORT}'
      COMPRESSION_DB_USER: '${COMPRESSION_DB_USER}'
      COMPRESSION_DB_PASSWORD: '${COMPRESSION_DB_PASSWORD}'
      COMPRESSION_S3_HOST: '${COMPRESSION_S3_HOST}'   
      COMPRESSION_S3_REGION: '${COMPRESSION_S3_REGION}'
      COMPRESSION_S3_SERVICE: '${COMPRESSION_S3_SERVICE}'
      COMPRESSION_S3_ENV: '${COMPRESSION_S3_ENV}'
    type: Opaque

parameters:
  - name: NAME
    description: The name for all created objects.
    required: true
  - name: COMPRESSION_REDIS_HOST
    description: COMPRESSION_REDIS_HOST
    required: true
  - name: COMPRESSION_REDIS_PASSWORD
    description: COMPRESSION_REDIS_PASSWORD
    required: true
  - name: COMPRESSION_REDIS_PORT
    description: COMPRESSION_REDIS_PORT
    required: true
  - name: COMPRESSION_STREAM_KEY
    description: COMPRESSION_STREAM_KEY
    required: true
  - name: COMPRESSION_DB_HOST
    description: COMPRESSION_DB_HOST
    required: true
  - name: COMPRESSION_DB_NAME
    description: COMPRESSION_DB_NAME
    required: true
  - name: COMPRESSION_DB_PORT
    description: COMPRESSION_DB_PORT
    required: true
  - name: COMPRESSION_DB_USER
    description: COMPRESSION_DB_USER
    required: true
  - name: COMPRESSION_DB_PASSWORD
    description: COMPRESSION_DB_PASSWORD
    required: true
  - name: COMPRESSION_S3_HOST
    description: COMPRESSION_S3_HOST
    required: true  
  - name: COMPRESSION_S3_REGION
    description: COMPRESSION_S3_REGION
    required: true
  - name: COMPRESSION_S3_SERVICE
    description: COMPRESSION_S3_SERVICE
    required: true
  - name: COMPRESSION_S3_ENV
    description: COMPRESSION_S3_ENV
    required: true