"""empty message

Revision ID: 04a2c961fadc
Revises: 914a92625c03
Create Date: 2023-03-27 13:20:28.722935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '04a2c961fadc'
down_revision = '92e790437c06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DocumentDeleted', sa.Column('ministryrequestid', sa.Integer, unique=False, nullable=True, default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DocumentDeleted', 'ministryrequestid')
    # ### end Alembic commands ###
