"""empty message

Revision ID: 18a45d1b33cc
Revises: 7db1cd6f0b36
Create Date: 2024-03-07 10:00:01.341943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '18a45d1b33cc'
down_revision = 'c787e6d82903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DocumentDeletedPages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ministryrequestid', sa.Integer(), nullable=False),
    sa.Column('redactionlayerid', sa.Integer(), nullable=False),
    sa.Column('documentid', sa.Integer(), nullable=False),
    sa.Column('pagemetadata',  postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('createdby', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    )
    op.add_column('Documents', sa.Column('originalpagecount', sa.Integer, unique=False, nullable=True, default=False))
    op.execute('UPDATE "Documents"  SET originalpagecount  = pagecount, updatedby= \'{"user":"System"}\', updated_at=now();commit;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DocumentDeletedPages')
    op.drop_column('Documents', 'originalpagecount')
    # ### end Alembic commands ###
