"""empty message

Revision ID: 36e7b771fbb5
Revises: 6ae89a54cb75
Create Date: 2023-08-24 16:02:36.607780

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36e7b771fbb5'
down_revision = '6ae89a54cb75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE public."Annotations" ADD CONSTRAINT annotation_version_key UNIQUE (annotationname, version);')
    op.execute('ALTER TABLE public."AnnotationSections" ADD CONSTRAINT annotationsection_version_key UNIQUE (annotationname, version);')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE public."Annotations" DROP CONSTRAINT "annotation_version_key";')
    op.execute('ALTER TABLE public."AnnotationSections" DROP CONSTRAINT "annotationsection_version_key";')
    # ### end Alembic commands ###
