"""empty message

Revision ID: 374a9a0b07e8
Revises: ae4f8e0d58b2
Create Date: 2024-12-13 14:52:49.688416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '374a9a0b07e8'
down_revision = 'ae4f8e0d58b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DocumentExtractionJob',   
    sa.Column('extractionjobid', sa.Integer(), primary_key=True, autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('documentid', sa.Integer(), nullable=False),        
    sa.Column('ministryrequestid', sa.Integer(), nullable=False),        
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('createdat', sa.TIMESTAMP, nullable=False, server_default=sa.func.now()),
    sa.Column('createdby', sa.String(length=120), nullable=True), 
    sa.PrimaryKeyConstraint('extractionjobid'),
    )

    op.execute(
        'CREATE INDEX "idx_documentextractionjob_multicolumn" ON "DocumentExtractionJob" (extractionjobid, version, documentid, ministryrequestid, status);'
    )
    op.execute(
        'ALTER TABLE "DocumentExtractionJob" ADD CONSTRAINT "unique_documentextractionjob" UNIQUE (extractionjobid, version, documentid, ministryrequestid, status);'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX "idx_documentextractionjob_multicolumn";')
    op.execute('ALTER TABLE "DocumentExtractionJob" DROP CONSTRAINT "unique_documentextractionjob";')
    op.drop_table('DocumentExtractionJob')
    # ### end Alembic commands ###
