"""Add new fields & DocumentProcesses table for compression

Revision ID: 3ab3c837fc93
Revises: 50b4dc64d6cd
Create Date: 2025-04-30 10:33:32.771697

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3ab3c837fc93'
down_revision = '50b4dc64d6cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    document_status_table = op.create_table('DocumentProcesses',
        sa.Column('processid', sa.Integer(), primary_key=True, autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('isactive', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('processid')
    )

    op.bulk_insert(
        document_status_table,
        [
            {'name':'dedupe', 'isactive':True, 'description': 'Conversion and Dedupe'},
            {'name':'compression', 'isactive':True, 'description': 'Compression'},
            {'name':'ocr', 'isactive':True, 'description': 'OCR'}
        ]
    )

    op.add_column('DocumentMaster', sa.Column('compressedfilepath', sa.String(length=500), nullable=True))
    op.add_column('Documents', sa.Column('selectedfileprocessversion', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Documents', 'DocumentProcesses', ['selectedfileprocessversion'], ['processid'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DocumentMaster', 'compressedfilepath')
    op.drop_column('Documents', 'selectedfileprocessversion')
    op.drop_table('DocumentProcesses')
    # ### end Alembic commands ###
