"""empty message

Revision ID: 48191befb823
Revises: fa372bcf451e
Create Date: 2023-02-07 13:20:22.850087

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import column, table
from sqlalchemy.sql.sqltypes import Boolean, String, Integer
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision = '48191befb823'
down_revision = 'fa372bcf451e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Sections',
    sa.Column('sectionid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('sortorder', sa.Integer(), nullable=True),
    sa.Column('isactive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True,server_default=func.now()),
    sa.Column('createdby', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),    
    sa.Column('updatedby', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('sectionid')
    )
    section_table = table('Sections',
                                 column('section',String),
                                 column('description',String),
                                 column('isactive',Boolean),
                                 column('createdby',String),
                                 column('sortorder',Integer),
                                   )
    op.bulk_insert(
        section_table,
        [
            {"section":"s. 12","description":"Cabinet and local public body confidences","isactive":True, "createdby": "System","sortorder":1},
            {"section":"s. 13","description":"Policy advice or recommendations","isactive":True, "createdby": "System","sortorder":2},
            {"section":"s. 14","description":"Legal advice","isactive":True, "createdby": "System","sortorder":3},
            {"section":"s. 15","description":"Disclosure harmful to law enforcement","isactive":True, "createdby": "System","sortorder":4},
            {"section":"s. 16","description":"Disclosure harmful to intergovernmental relations or negotiations","isactive":True, "createdby": "System","sortorder":5},
            {"section":"s. 17","description":"Disclosure harmful to the financial or economic interests of a public body","isactive":True, "createdby": "System","sortorder":6},
            {"section":"s. 18","description":"Disclosure harmful to the conservation of heritage sites","isactive":True, "createdby": "System","sortorder":7},
            {"section":"s. 18.1","description":"Disclosure harmful to interests of an Indigenous people","isactive":True, "createdby": "System","sortorder":8},
            {"section":"s. 19","description":"Disclosure harmful to individual or public safety","isactive":True, "createdby": "System","sortorder":9},
            {"section":"s. 20","description":"Information that will be published within 60 days","isactive":True, "createdby": "System","sortorder":10},
            {"section":"s. 21","description":"Disclosure harmful to the business interests of a third party","isactive":True, "createdby": "System","sortorder":11},
            {"section":"s. 22","description":"Disclosure harmful to personal privacy","isactive":True, "createdby": "System","sortorder":12},
            {"section":"s. 22.1","description":"Disclosure of information relating to abortion services","isactive":True, "createdby": "System","sortorder":13},
            {"section":"s. 3","description":"Scope of Act","isactive":True, "createdby": "System","sortorder":14},
            {"section":"s. 3 - CFCSA s. 24","description":"Confidentiality of information under CFCSA","isactive":True, "createdby": "System","sortorder":15},
            {"section":"s. 3 - CFCSA s. 77(1)","description":"Identity of a Reporter under CFCSA","isactive":True, "createdby": "System","sortorder":16},
            {"section":"s. 3 - CFCSA s. 77(2)(a)","description":"Jeopardize an investigation under CFCSA","isactive":True, "createdby": "System","sortorder":17},
            {"section":"s. 3 - CFCSA s. 77(2)(b)","description":"Information collected in confidence under CFCSA Investigation","isactive":True, "createdby": "System","sortorder":18},
            {"section":"s. 3 - AA s. 73","description":"Restriction on use and disclosure of certain information, Adoption Act","isactive":True, "createdby": "System","sortorder":19},
            {"section":"s. 3 - AGA s. 46","description":"Reporting abuse or neglect, Adult Guardianship Act","isactive":True, "createdby": "System","sortorder":20},
            {"section":"s. 3 - CA s. 63","description":"General prohibition against disclosure, Coroner's Act","isactive":True, "createdby": "System","sortorder":21},
            {"section":"s. 3 - CA s. 64","description":"Application of FOIPPA, Coroner's Act","isactive":True, "createdby": "System","sortorder":22},
            {"section":"s. 3 - FMEA s. 43","description":"Confidential Information, Family Maintenance Enforcement Act","isactive":True, "createdby": "System","sortorder":23},
            {"section":"s. 3 - PA","description":"Police Act","isactive":True, "createdby": "System","sortorder":24},
            {"section":"","description":"Blank Code - CFD Personals","isactive":True, "createdby": "System","sortorder":25},
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Sections')
    # ### end Alembic commands ###
