"""Compression Job Table

Revision ID: 50b4dc64d6cd
Revises: 828d870c000f
Create Date: 2025-04-04 11:40:38.782986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50b4dc64d6cd'
down_revision = '828d870c000f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CompressionJob',
        sa.Column('compressionjobid', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('ministryrequestid', sa.Integer(), nullable=False),
        sa.Column('createdat', sa.TIMESTAMP, nullable=False, server_default=sa.func.now()),
        sa.Column('batch', sa.String(length=120), nullable=False), 
        sa.Column('trigger', sa.String(length=120), nullable=False), 
        sa.Column('filename', sa.String(length=500), nullable=False), 
        sa.Column('status', sa.String(length=120), nullable=False), 
        sa.Column('message', sa.Text, nullable=True),
        sa.Column('documentmasterid', sa.Integer(), nullable=False), 
        sa.PrimaryKeyConstraint('compressionjobid', 'version')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CompressionJob')
    # ### end Alembic commands ###
