"""empty message

Revision ID: 549893ea9059
Revises: 2045c976ea60
Create Date: 2023-11-23 22:53:32.071886

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '549893ea9059'
down_revision = '2045c976ea60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AnnotationSections', sa.Column('redactionlayerid', sa.Integer, nullable=False, server_default='1'))
    op.create_foreign_key(None, 'AnnotationSections', 'RedactionLayers', ['redactionlayerid'], ['redactionlayerid'])
    op.execute(
        'ALTER TABLE public."AnnotationSections" DROP CONSTRAINT "annotationsection_version_key";'
    )
    op.execute(
        'ALTER TABLE public."AnnotationSections" ADD CONSTRAINT annotationsection_version_redactionlayerid_key UNIQUE (annotationname, version, redactionlayerid);'
    )
    op.execute('Update public."AnnotationSections" set redactionlayerid = 1 where redactionlayerid is null ')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AnnotationSections', 'redactionlayerid')
    op.execute(
        'ALTER TABLE public."AnnotationSections" DROP CONSTRAINT "annotationsection_version_redactionlayerid_key";'
    )
    op.execute(
        'ALTER TABLE public."AnnotationSections" ADD CONSTRAINT annotationsection_version_key UNIQUE (annotationname, version);'
    )
    # ### end Alembic commands ###
