"""Pageflags - Add Phase flag

Revision ID: 5ace86cdb21d
Revises: 828d870c000f
Create Date: 2025-01-29 19:42:50.888620

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ace86cdb21d'
down_revision = '828d870c000f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        'INSERT INTO public."Pageflags"(name, description, isactive, createdby, sortorder) VALUES (\'Phase\', \'Phase\', True, \'System\', 8);commit;') 

    op.execute('UPDATE public."Pageflags" set sortorder=9 where "Pageflags".name =\'Page Left Off\';commit;')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('delete from public."Pageflags" WHERE name in (\'Phase\');commit;')
    op.execute('UPDATE public."Pageflags" set sortorder=8 where "Pageflags".name =\'Page Left Off\';commit;')
    # ### end Alembic commands ###
