"""empty message

Revision ID: 6ae89a54cb75
Revises: b9a82a00b13a
Create Date: 2023-08-22 10:32:25.292605

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6ae89a54cb75'
down_revision = 'b9a82a00b13a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Annotations', sa.Column('version', sa.Integer, nullable=False, server_default="1"))
    op.execute('ALTER TABLE public."Annotations" DROP CONSTRAINT "Annotations_pkey";')
    op.execute('ALTER TABLE public."Annotations" ADD PRIMARY KEY (annotationid, version);')
    op.execute('ALTER TABLE public."Annotations" DROP CONSTRAINT "Annotations_annotationname_key" CASCADE;')    
    op.add_column('AnnotationSections', sa.Column('version', sa.Integer, nullable=False, server_default="1"))
    op.add_column('AnnotationSections', sa.Column('isactive', sa.Boolean, nullable=False, server_default="True"))
    op.execute('ALTER TABLE public."AnnotationSections" DROP CONSTRAINT "AnnotationSections_pkey";')
    op.execute('ALTER TABLE public."AnnotationSections" ADD PRIMARY KEY (id, version);')
    op.execute('ALTER TABLE public."AnnotationSections" DROP CONSTRAINT "AnnotationSections_annotationname_key" CASCADE;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###    
    op.execute("""delete from "Annotations" ax 
                    where (annotationid, "version") not in (select distinct on (annotationid) annotationid, "version"  
                    from "Annotations" 
                    order by annotationid, version desc);
    """
    )
    op.execute('ALTER TABLE public."Annotations" DROP CONSTRAINT "Annotations_pkey";')
    op.drop_column('Annotations', 'version')
    op.execute('ALTER TABLE public."Annotations" ADD PRIMARY KEY (annotationid);')
    op.execute('ALTER TABLE public."Annotations" ADD CONSTRAINT "Annotations_annotationname_key" UNIQUE(annotationname);')
    op.execute("""delete from "AnnotationSections" ax 
                    where (id, "version") not in (select distinct on (id) id, "version"  
                    from "AnnotationSections" 
                    order by id, version desc);
    """
    )
    op.execute('ALTER TABLE public."AnnotationSections" DROP CONSTRAINT "AnnotationSections_pkey";')
    op.drop_column('AnnotationSections', 'version')
    op.drop_column('AnnotationSections', 'isactive')
    op.execute('ALTER TABLE public."AnnotationSections" ADD PRIMARY KEY (id);')
    op.execute('ALTER TABLE public."AnnotationSections" ADD CONSTRAINT "AnnotationSections_annotationname_key" UNIQUE(annotationname);')
   
   # ### end Alembic commands ###
