"""empty message

Revision ID: 71dd0db2ef70
Revises: bef255d2e065
Create Date: 2023-03-06 10:30:35.519372

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import column, table
from sqlalchemy.sql.sqltypes import Boolean, String, Integer
from sqlalchemy.sql import func

# revision identifiers, used by Alembic.
revision = '71dd0db2ef70'
down_revision = '641ae620392d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pageflags',
    sa.Column('pageflagid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('sortorder', sa.Integer(), nullable=True),
    sa.Column('isactive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True,server_default=func.now()),
    sa.Column('createdby', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),    
    sa.Column('updatedby', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('pageflagid')
    )
    pageflag_table = table('Pageflags',
                                 column('name',String),
                                 column('description',String),
                                 column('sortorder',Integer),
                                 column('isactive',Boolean),
                                 column('createdby',String),                                 
                                   )
    op.bulk_insert(
        pageflag_table,
        [
            {"name":"Partial Disclosure","description":"Partial Disclosure","isactive":True, "createdby": "System","sortorder":1},
            {"name":"Full Disclosure","description":"Full Disclosure","isactive":True, "createdby": "System","sortorder":2},
            {"name":"Withheld in Full","description":"Withheld in Full","isactive":True, "createdby": "System","sortorder":3},
            {"name":"Consult","description":"Consult","isactive":True, "createdby": "System","sortorder":4},
            {"name":"Duplicate","description":"Duplicate","isactive":True, "createdby": "System","sortorder":5},
            {"name":"Not Responsive","description":"Not Responsive","isactive":True, "createdby": "System","sortorder":6},
            {"name":"Page Left Off","description":"Page Left Off","isactive":True, "createdby": "System","sortorder":7}
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Pageflags')
    # ### end Alembic commands ###
