"""empty message

Revision ID: 7db1cd6f0b36
Revises: 549893ea9059
Create Date: 2024-03-15 13:30:30.604299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db1cd6f0b36'
down_revision = '549893ea9059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        'CREATE INDEX "idx_documentpgflag_multicolumn" ON "DocumentPageflags" (foiministryrequestid, documentid, documentversion, redactionlayerid);'
    )
    op.execute(
        'ALTER TABLE "DocumentPageflags" ADD CONSTRAINT "unique_documentpgflag" UNIQUE (foiministryrequestid, documentid, documentversion, redactionlayerid);'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX "idx_documentpgflag_multicolumn";')
    op.execute('ALTER TABLE "DocumentPageflags" DROP CONSTRAINT "unique_documentpgflag";')
    # ### end Alembic commands ###
