"""empty message

Revision ID: 81eb14daaace
Revises: 6e91c6b84964
Create Date: 2024-10-28 09:07:42.841630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import column, table
from sqlalchemy.sql.sqltypes import Boolean, String, Integer
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision = '81eb14daaace'
down_revision = '6e91c6b84964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OIRedactionCodes',
    sa.Column('redactioncodeid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('redactioncode', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('sortorder', sa.Integer(), nullable=True),
    sa.Column('isactive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True,server_default=func.now()),
    sa.Column('createdby', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),    
    sa.Column('updatedby', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('redactioncodeid')
    )
    redactioncode_table = table('OIRedactionCodes',
                                 column('redactioncode',String),
                                 column('description',String),
                                 column('isactive',Boolean),
                                 column('createdby',String),
                                 column('sortorder',Integer),
                                   )
    op.bulk_insert(
        redactioncode_table,
        [
            {"redactioncode":"Copyright Information","description":"Copyright Information","isactive":True, "createdby": "System","sortorder":1},
            {"redactioncode":"Cabinet Confidences","description":"Cabinet Confidences","isactive":True, "createdby": "System","sortorder":2},
            {"redactioncode":"Advice/Recommendations","description":"Advice/Recommendations","isactive":True, "createdby": "System","sortorder":3},
            {"redactioncode":"Legal Information","description":"Legal Information","isactive":True, "createdby": "System","sortorder":4},
            {"redactioncode":"Security Concern","description":"Security Concern","isactive":True, "createdby": "System","sortorder":5},
            {"redactioncode":"Intergovernmental Communications","description":"Intergovernmental Communications","isactive":True, "createdby": "System","sortorder":6},
            {"redactioncode":"Interests of an Indigenous People","description":"Interests of an Indigenous People","isactive":True, "createdby": "System","sortorder":7},
            {"redactioncode":"Government Financial Information","description":"Government Financial Information","isactive":True, "createdby": "System","sortorder":8},
            {"redactioncode":"Conservation of Heritage Sites","description":"Conservation of Heritage Sites","isactive":True, "createdby": "System","sortorder":9},
            {"redactioncode":"Personal Security","description":"Personal Security","isactive":True, "createdby": "System","sortorder":10},
            {"redactioncode":"Business Information","description":"Business Information","isactive":True, "createdby": "System","sortorder":11},
            {"redactioncode":"Personal Information","description":"Personal Information","isactive":True, "createdby": "System","sortorder":12},
            {"redactioncode":"Court Records","description":"Court Records","isactive":True, "createdby": "System","sortorder":13},
            {"redactioncode":"Application","description":"Application","isactive":True, "createdby": "System","sortorder":14},
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OIRedactionCodes')
    # ### end Alembic commands ###
