"""empty message

Revision ID: 914a92625c03
Revises: 71dd0db2ef70
Create Date: 2023-03-07 15:08:22.764321

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '914a92625c03'
down_revision = '71dd0db2ef70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DocumentPageflags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('foiministryrequestid', sa.Integer(), nullable=False),
    sa.Column('documentid', sa.Integer(), nullable=False),
    sa.Column('documentversion', sa.Integer(), nullable=False),
    sa.Column('pageflag',  postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('attributes',  postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('createdby', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),    
    sa.Column('updatedby',  postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['documentid', 'documentversion'], ['Documents.documentid', 'Documents.version'])
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DocumentPageflags') 
    # ### end Alembic commands ###
