"""empty message

Revision ID: a5254d701e1f
Revises: 04a2c961fadc
Create Date: 2023-04-10 10:11:27.509774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a5254d701e1f'
down_revision = '04a2c961fadc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE public."Documents" ALTER COLUMN filename TYPE VARCHAR(500)')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE public."Documents" ALTER COLUMN filename TYPE VARCHAR(120)')
    # ### end Alembic commands ###
