"""empty message

Revision ID: ae4f8e0d58b2
Revises: 9d45ce57481e
Create Date: 2024-12-13 12:24:11.094340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ae4f8e0d58b2'
down_revision = '9d45ce57481e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('UPDATE public."DocumentStatus" SET name=\'pushedtoqueue\', description= \'Pushed to queue\' WHERE name in (\'inprogress\');commit;')
    op.execute('UPDATE public."DocumentStatus" SET name=\'extractioncompleted\', description= \'Extraction completed\' WHERE name in (\'saved\');commit;')
    op.execute('INSERT INTO public."DocumentStatus"(name, description, isactive) VALUES (\'failed\', \'Failed\', true);commit;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('UPDATE public."DocumentStatus" SET name=\'inprogress\', description=\'In progress\' WHERE name in (\'pushedtoqueue\');commit;')
    op.execute('UPDATE public."DocumentStatus" SET name=\'saved\', description=\'Saved\' WHERE name in (\'extractioncompleted\');commit;')
    op.execute('delete from public."DocumentStatus" WHERE name in (\'failed\');commit;')
    # ### end Alembic commands ###
