"""empty message

Revision ID: bef255d2e065
Revises: 48191befb823
Create Date: 2023-02-08 14:05:54.958041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bef255d2e065'
down_revision = '48191befb823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AnnotationSections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('annotationname', sa.String(), unique=True, nullable=False),
    sa.Column('foiministryrequestid', sa.Integer(), nullable=False),
    sa.Column('section', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('createdby', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),    
    sa.Column('updatedby', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['annotationname'], ['Annotations.annotationname'])
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AnnotationSections')
    # ### end Alembic commands ###
