"""OCR Job related fields & tables

Revision ID: db37962dca5b
Revises: 3ab3c837fc93
Create Date: 2025-05-06 13:00:00.916705

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db37962dca5b'
down_revision = '3ab3c837fc93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OCRActiveMQJob',
        sa.Column('ocractivemqjobid', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('ministryrequestid', sa.Integer(), nullable=False),
        sa.Column('createdat', sa.TIMESTAMP, nullable=False, server_default=sa.func.now()),
        sa.Column('batch', sa.String(length=120), nullable=False), 
        sa.Column('trigger', sa.String(length=120), nullable=False), 
        sa.Column('filename', sa.String(length=500), nullable=False), 
        sa.Column('status', sa.String(length=120), nullable=False), 
        sa.Column('message', sa.Text, nullable=True),
        sa.Column('documentmasterid', sa.Integer(), nullable=False), 
        sa.PrimaryKeyConstraint('ocractivemqjobid', 'version')
    )
    op.add_column('DocumentMaster', sa.Column('ocrfilepath', sa.String(length=500), nullable=True))

    op.create_table('DocumentOCRJob',   
        sa.Column('ocrjobid', sa.Integer(), primary_key=True, autoincrement=True, nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('documentid', sa.Integer(), nullable=False),        
        sa.Column('ministryrequestid', sa.Integer(), nullable=False),  
        sa.Column('documentmasterid', sa.Integer(), nullable=False),        
        sa.Column('status', sa.String(length=120), nullable=False),
        sa.Column('message', sa.Text(), nullable=True),
        sa.Column('createdat', sa.TIMESTAMP, nullable=False, server_default=sa.func.now()),
        sa.Column('createdby', sa.String(length=120), nullable=True), 
        sa.PrimaryKeyConstraint('ocrjobid'),
    )

    op.execute(
        'CREATE INDEX "idx_documentocrjob_multicolumn" ON "DocumentOCRJob" (ocrjobid, version, documentid, ministryrequestid, status);'
    )
    op.execute(
        'ALTER TABLE "DocumentOCRJob" ADD CONSTRAINT "unique_documentocrjob" UNIQUE (ocrjobid, version, documentid, ministryrequestid, status);'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OCRJob')
    op.drop_column('DocumentMaster', 'ocrfilepath')
    
    op.execute('DROP INDEX "idx_documentocrjob_multicolumn";')
    op.execute('ALTER TABLE "DocumentOCRJob" DROP CONSTRAINT "unique_documentocrjob";')
    op.drop_table('DocumentOCRJob')
    # ### end Alembic commands ###
