"""empty message

Revision ID: e7abeeb1aad1
Revises: 427683d4852a
Create Date: 2023-07-07 09:35:07.014076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import column, table
from sqlalchemy.sql.sqltypes import Boolean, String, Integer
from sqlalchemy.sql import func

# revision identifiers, used by Alembic.
revision = 'e7abeeb1aad1'
down_revision = '427683d4852a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Keywords',
    sa.Column('keywordid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=1000), nullable=False),
    sa.Column('category', sa.String(length=500), nullable=False),
    sa.Column('isactive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True,server_default=func.now()),
    sa.Column('createdby', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),    
    sa.Column('updatedby', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('keywordid')
    )
    keywords_table = table('Keywords',
                                 column('keyword',String),
                                 column('category',String),
                                 column('version',Integer),
                                 column('isactive',Boolean),
                                 column('createdby',String),                                 
                                   )
    op.bulk_insert(
        keywords_table,
        [
            {"keyword":"Legal counsel","category":"Legal",'version':1,"isactive":True, "createdby": "System"},
            {"keyword":"legal advice","category":"Legal",'version':1,"isactive":True, "createdby": "System"},
            {"keyword":"legal advise","category":"Legal",'version':1,"isactive":True, "createdby": "System"},
            {"keyword":"solicitor client privilege","category":"Legal",'version':1,"isactive":True, "createdby": "System"},
            {"keyword":"privileged","category":"Legal",'version':1,"isactive":True, "createdby": "System"},
            {"keyword":"lawyer","category":"Legal",'version':1,"isactive":True, "createdby": "System"},
            {"keyword":"LSB","category":"Legal",'version':1,"isactive":True, "createdby": "System"},
            {"keyword":"DAG","category":"Legal",'version':1,"isactive":True, "createdby": "System"},
            {"keyword":"Legal Service Branch","category":"Legal",'version':1,"isactive":True, "createdby": "System"},
            {"keyword":"Deputy Attorney General","category":"Legal",'version':1,"isactive":True, "createdby": "System"},
            {"keyword":"Legal Services Branch","category":"Legal",'version':1,"isactive":True, "createdby": "System"},
            {"keyword":"litigation","category":"Legal",'version':1,"isactive":True, "createdby": "System"},
            {"keyword":"privilege","category":"Legal",'version':1,"isactive":True, "createdby": "System"}
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Keywords')
    # ### end Alembic commands ###
