"""empty message

Revision ID: ffaeedd62e37
Revises: e7abeeb1aad1
Create Date: 2023-08-04 11:40:56.310121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ffaeedd62e37'
down_revision = 'e7abeeb1aad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RedactionLayers',
        sa.Column('redactionlayerid', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('sortorder', sa.Integer(), nullable=True),
        sa.Column('isactive', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('createdby', sa.String(length=120), nullable=True),
        sa.Column('updatedby', sa.String(length=120), nullable=True),
        sa.PrimaryKeyConstraint('redactionlayerid')
    )
    op.execute('INSERT INTO public."RedactionLayers"(name, description, sortorder, isactive, createdby, created_at) VALUES (\'Redline\', \'Redline\', 1, True, \'System\', now());commit;') 
    op.execute('INSERT INTO public."RedactionLayers"(name, description, sortorder, isactive, createdby, created_at) VALUES (\'Response Package\', \'Response Package\', 2, True, \'System\', now());commit;') 
    op.execute('INSERT INTO public."RedactionLayers"(name, description, sortorder, isactive, createdby, created_at) VALUES (\'OIPC\', \'OIPC\', 3, True, \'System\', now());commit;') 
    op.add_column('Annotations', sa.Column('redactionlayerid', sa.Integer, nullable=False, server_default='1'))
    op.create_foreign_key(None, 'Annotations', 'RedactionLayers', ['redactionlayerid'], ['redactionlayerid'])
    op.execute('Update public."Annotations" set redactionlayerid = 1 where redactionlayerid is null ')
    # ### end Alembic commands #### ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Annotations', 'redactionlayerid')
    op.drop_table('RedactionLayers')    
    # ### end Alembic commands ###
