services:
  - name: reviewer-zippingservice
    path: computingservices/ZippingServices
    image: reviewer-zippingservice
    kind: deployments
    deploymentOverride:
      test: reviewer-zippingservice-test

  - name: reviewer-documentservice
    path: computingservices/DocumentServices
    image: reviewer-documentservice
    kind: deployments

  - name: reviewer-conversion
    path: MCS.FOI.S3FileConversion
    image: reviewer-conversion
    kind: deployments
    largefiles: true

  - name: reviewer-pdfstitch
    path: computingservices/PDFStitchServices
    image: reviewer-pdfstitch
    kind: deployments
    largefiles: true

  - name: reviewer-api
    path: api
    image: reviewer-api
    kind: deployments

  - name: reviewer-pagecountcalculator
    path: computingservices/PageCountCalculator
    image: reviewer-pagecountcalculator
    kind: deployments

  - name: reviewer-ocr
    path: computingservices/OCRServices
    image: reviewer-ocr
    kind: deployments
    largefiles: true

  - name: reviewer-dedupe
    path: computingservices/DedupeServices
    image: reviewer-dedupe
    kind: deployments
    largefiles: true

  - name: reviewer-compression
    path: computingservices/CompressionServices
    image: reviewer-compression
    kind: deployments
    largefiles: true

  - name: azuredocextractauditapi
    path: azuredocextractapi
    image: azuredocextractauditapi
    kind: deployments
    deploymentOverride:
      dev: azuredocextractauditapi-dev
      test: azuredocextractauditapi-test
      prod: azuredocextractauditapi-prod

  - name: azure-doc-ocr-api
    path: azuredococrapi
    image: azuredococrapi
    kind: deployments

  - name: reviewer-web
    path: web
    image: reviewer-web
    kind: deployments

  - name: etl-task
    path: computingservices/ETLServices
    image: reviewer-etlservices
    kind: cronJobs