name: DEV API CD


on:
  push:
    branches:
      # - dev
      - dev-RQ-2956-new
    paths:
      - "api/**"
      - ".github/workflows/api-cd.dev.yml"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (dev/test/prod)"
        required: true
        default: "dev"

defaults:
  run:
    shell: bash
    working-directory: ./api

env:
  APP_NAME: "reviewer-api"
  TAG_NAME: "dev"

jobs:
  api-cd-by-push:
    runs-on: ubuntu-20.04

    if: github.event_name == 'push' && github.repository == 'bcgov/foi-docreviewer'
    environment:
      name: "dev"

    steps:
      - uses: actions/checkout@v2

      - name: Login Openshift
        shell: bash
        run: |
          oc login --server=${{secrets.OPENSHIFT4_LOGIN_REGISTRY}} --token=${{secrets.OPENSHIFT4_SA_TOKEN}}

      - name: Tools project
        shell: bash
        run: |
          oc project ${{ secrets.OPENSHIFT4_FRONTEND_REPOSITORY }}-tools

      - name: Build from dev branch
        shell: bash
        run: |
          oc patch bc/${{ env.APP_NAME }}-build -p '{"spec":{"source":{"git":{"ref":"dev-RQ-2956-new"}}}}'

      - name: Start Build Openshift
        shell: bash
        run: |
          oc start-build ${{ env.APP_NAME }}-build --wait

      - name: Tag+Deploy for DEV
        shell: bash
        run: |
          oc tag ${{ env.APP_NAME }}:latest ${{ env.APP_NAME }}:dev

      # - name: Watch new rollout (trigger by image change in Openshift)
      #   shell: bash
      #   run: |
      #     oc rollout status dc/${{ env.APP_NAME }} -n ${{ secrets.OPENSHIFT4_FRONTEND_REPOSITORY }}-${{ env.TAG_NAME }} -w

      # - name: Rocket.Chat Notification
      #   uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
      #   if: failure()
      #   with:
      #     type: ${{ job.status }}
      #     job_name: "*Auth Web Built and Deployed to ${{env.TAG_NAME}}*"
      #     channel: "#registries-bot"
      #     url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
      #     commit: true
      #     token: ${{ secrets.GITHUB_TOKEN }}
