name: OCR CD

on:
  push:
    branches:
      - dev
      - main
      - dev-marshal
      - test-marshal
      - dev-rook
      - test-rook
    paths:
      - "computingservices/OCRServices/**"
      - ".github/workflows/ocrservice-cd.yml"

defaults:
  run:
    shell: bash
    working-directory: ./computingservices/OCRServices

env:
  APP_NAME: "reviewer-ocr"
  TOOLS_NAME: "${{ secrets.OPENSHIFT4_REPOSITORY }}"

jobs:
  ocr-cd-by-push:
    runs-on: ubuntu-24.04

    if: github.event_name == 'push' && github.repository == 'bcgov/foi-docreviewer'
    
    steps:
      - name: Install oc
        uses: redhat-actions/oc-installer@v1
        with:
          oc_version: '4.6'

      - uses: actions/checkout@v2

      - name: Set ENV variables for dev branch
        if: ${{ github.ref_name == 'dev' }}
        run: |
          echo "TAG_NAME=dev" >> $GITHUB_ENV
          echo "BRANCH_NAME=dev" >> $GITHUB_ENV
          echo "ENV_NAME=dev" >> $GITHUB_ENV

      - name: Set ENV variables for main branch
        if: ${{ github.ref_name == 'main' }}
        run: |
          echo "TAG_NAME=test" >> $GITHUB_ENV
          echo "BRANCH_NAME=main" >> $GITHUB_ENV
          echo "ENV_NAME=test" >> $GITHUB_ENV

      - name: Set ENV variables for dev-marshal branch
        if: ${{ github.ref_name == 'dev-marshal' }}
        run: |
          echo "TAG_NAME=dev-marshal" >> $GITHUB_ENV
          echo "BRANCH_NAME=dev-marshal" >> $GITHUB_ENV
          echo "ENV_NAME=dev" >> $GITHUB_ENV

      - name: Set ENV variables for test-marshal branch
        if: ${{ github.ref_name == 'test-marshal' }}
        run: |
          echo "TAG_NAME=test-marshal" >> $GITHUB_ENV
          echo "BRANCH_NAME=test-marshal" >> $GITHUB_ENV
          echo "ENV_NAME=test" >> $GITHUB_ENV

      - name: Set ENV variables for dev-rook branch
        if: ${{ github.ref_name == 'dev-rook' }}
        run: |
          echo "TAG_NAME=dev-rook" >> $GITHUB_ENV
          echo "BRANCH_NAME=dev-rook" >> $GITHUB_ENV
          echo "ENV_NAME=dev" >> $GITHUB_ENV
          echo "ENV_TAG_NAME=rook" >> $GITHUB_ENV

      - name: Set ENV variables for test-rook branch
        if: ${{ github.ref_name == 'test-rook' }}
        run: |
          echo "TAG_NAME=test-rook" >> $GITHUB_ENV
          echo "BRANCH_NAME=test-rook" >> $GITHUB_ENV
          echo "ENV_NAME=test" >> $GITHUB_ENV
          echo "ENV_TAG_NAME=rook" >> $GITHUB_ENV

      - name: Login to OpenShift
        run: |
          oc login --server=${{ secrets.OPENSHIFT4_LOGIN_REGISTRY }} --token=${{ secrets.OPENSHIFT4_SA_TOKEN }}

      - name: Switch to Tools project
        run: |
          oc project ${{ env.TOOLS_NAME }}-tools

      - name: Patch Build Config with correct branch and context
        run: |
          oc patch bc/${{ env.APP_NAME }}-build -p '{"spec":{"source":{"contextDir":"/computingservices/OCRServices","git":{"ref":"${{ env.BRANCH_NAME }}"}}}}'

      - name: Start OpenShift Build
        run: |
          oc start-build ${{ env.APP_NAME }}-build --wait

      - name: Trigger rollout by updating deployment image
        run: |
          oc set image deployment/${{ env.APP_NAME }} \
            ${{ env.APP_NAME }}=image-registry.openshift-image-registry.svc:5000/${{ env.TOOLS_NAME }}-tools/${{ env.APP_NAME }}:${{ env.TAG_NAME }} \
            -n ${{ env.TOOLS_NAME }}-${{ env.ENV_NAME }}

      - name: Watch new rollout (trigger by image change in Openshift)
        shell: bash
        run: |
          oc rollout status deployment/${{ env.APP_NAME }} -n ${{ env.TOOLS_NAME }}-${{ env.ENV_NAME }} -w
