name: Open Info Service CI


on:
  pull_request:
    branches:
      - main
      - dev
      - dev-marshal
      - test-marshal
      - dev-rook
      - test-rook
    paths:
      - "computingservices/OpenInfoServices/**"

defaults:
  run:
    shell: bash
    working-directory: ./computingservices/OpenInfoServices

jobs:
  docker-build-check:
    runs-on: ubuntu-latest
    name: Build dockerfile to ensure it works

    steps:
      - uses: actions/checkout@v2
      - name: docker build to check strictness
        id: docker-build
        run: |
          docker build -f Dockerfile.local .

  go-build-check:
    runs-on: ubuntu-latest
    name: Build go to ensure it works

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - name: Build the application
        run: go build -v .
      - name: Test the application
        run: go test ./...
