name: Zap Scanning

on:
  schedule:
    - cron: "0 11 * * *" # 3am pst
  push:
    branches:
      - dev
      - dev-ac-1398
      - dev-RQ-3026
    
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Manually trigger a ZAP Scan
        default: "dev"
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  zap_scan_frontend:
    runs-on: ubuntu-latest
    name: Scan the frontend
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          allow_issue_writing: false
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_title: 'ZAP Scan Report'
          target: ${{ secrets.ZAP_SCAN_FRONTEND_URL }}


  zap_scan_forms:
    runs-on: ubuntu-latest
    name: Scan the forms frontend
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          allow_issue_writing: false
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_title: 'ZAP Scan Report'
          target: ${{ secrets.ZAP_SCAN_FORMS_URL }}

  zap_scan_reviewer:
    runs-on: ubuntu-latest
    name: Scan the reviewer frontend
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          allow_issue_writing: false
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_title: 'ZAP Scan Report'
          target: ${{ secrets.ZAP_SCAN_REVIEWER_URL_DEV }}
          

  zap_scan_backend:
    runs-on: ubuntu-latest
    name: Scan the backend
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.6.0
        with:
          allow_issue_writing: false
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_title: 'ZAP Scan Report'
          target: ${{ secrets.ZAP_SCAN_BACKEND_URL_DEV }}