apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}
  labels:
    app: ${NAME}
    name: ${NAME}
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}
    stringData:    
      DOCREVIEWER_DB_HOST: "${DOCREVIEWER_DB_HOST}"
      DOCREVIEWER_DB_NAME: "${DOCREVIEWER_DB_NAME}"
      DOCREVIEWER_DB_USER: '${DOCREVIEWER_DB_USER}'
      DOCREVIEWER_DB_PASSWORD: '${DOCREVIEWER_DB_PASSWORD}'
      DOCREVIEWER_DB_PORT: '${DOCREVIEWER_DB_PORT}'
      FOI_DB_HOST: '${FOI_DB_HOST}'
      FOI_DB_NAME: '${FOI_DB_NAME}'
      FOI_DB_PORT: '${FOI_DB_PORT}'
      FOI_DB_USER: '${FOI_DB_USER}'
      FOI_DB_PASSWORD: '${FOI_DB_PASSWORD}'
      ACTIVEMQ_USERNAME: '${ACTIVEMQ_USERNAME}'
      ACTIVEMQ_PASSWORD: '${ACTIVEMQ_PASSWORD}'
      ACTIVEMQ_URL: '${ACTIVEMQ_URL}'

    type: Opaque

parameters:
  - name: NAME
    description: The name for all created objects.
    required: true
    value: docextractionqueuescheduler-secret-test-rook
  - name: DOCREVIEWER_DB_HOST
    description: DOCREVIEWER_DB_HOST
    required: true
  - name: DOCREVIEWER_DB_NAME
    description: DOCREVIEWER_DB_NAME
    required: true
  - name: DOCREVIEWER_DB_USER
    description: DOCREVIEWER_DB_USER
    required: true
  - name: DOCREVIEWER_DB_PASSWORD
    description: DOCREVIEWER_DB_PASSWORD
    required: true
  - name: DOCREVIEWER_DB_PORT
    description: DOCREVIEWER_DB_PORT
    required: true
  - name: FOI_DB_HOST
    description: FOI_DB_HOST
    required: true
  - name: FOI_DB_NAME
    description: FOI_DB_NAME
    required: true
  - name: FOI_DB_PORT
    description: FOI_DB_PORT
    required: true  
  - name: FOI_DB_USER
    description: FOI_DB_USER
    required: true
  - name: FOI_DB_PASSWORD
    description: FOI_DB_PASSWORD
    required: true
  - name: ACTIVEMQ_USERNAME
    description: ACTIVEMQ_USERNAME
    required: true 
  - name: ACTIVEMQ_PASSWORD
    description: ACTIVEMQ_PASSWORD
    required: true
  - name: ACTIVEMQ_URL
    description: ACTIVEMQ_URL
    required: true